/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace AgentRegistry {
      
    export type AgentStruct = {id: BigNumberish, owner: AddressLike, name: string, description: string, endpoint: string, capabilities: string[], active: boolean}

    export type AgentStructOutput = [id: bigint, owner: string, name: string, description: string, endpoint: string, capabilities: string[], active: boolean] & {id: bigint, owner: string, name: string, description: string, endpoint: string, capabilities: string[], active: boolean }
  
    }

  export interface AgentRegistryInterface extends Interface {
    getFunction(nameOrSignature: "agents" | "getAgent" | "nextAgentId" | "registerAgent"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AgentRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'agents', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAgent', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextAgentId', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerAgent', values: [string, string, string, string[]]): string;

    decodeFunctionResult(functionFragment: 'agents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextAgentId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerAgent', data: BytesLike): Result;
  }

  
    export namespace AgentRegisteredEvent {
      export type InputTuple = [id: BigNumberish, owner: AddressLike, name: string];
      export type OutputTuple = [id: bigint, owner: string, name: string];
      export interface OutputObject {id: bigint, owner: string, name: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AgentRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): AgentRegistry;
    waitForDeployment(): Promise<this>;

    interface: AgentRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    agents: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, string, boolean] & {id: bigint, owner: string, name: string, description: string, endpoint: string, active: boolean }],
      'view'
    >
    

    
    getAgent: TypedContractMethod<
      [id: BigNumberish, ],
      [AgentRegistry.AgentStructOutput],
      'view'
    >
    

    
    nextAgentId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    registerAgent: TypedContractMethod<
      [name: string, description: string, endpoint: string, capabilities: string[], ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'agents'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, string, boolean] & {id: bigint, owner: string, name: string, description: string, endpoint: string, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getAgent'): TypedContractMethod<
      [id: BigNumberish, ],
      [AgentRegistry.AgentStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'nextAgentId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'registerAgent'): TypedContractMethod<
      [name: string, description: string, endpoint: string, capabilities: string[], ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AgentRegistered'): TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;

    filters: {
      
      'AgentRegistered(uint256,address,string)': TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
      AgentRegistered: TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
    
    };
  }